instance_type="t2.micro"
region="us-east-1"
profile="dev"
ami_filter_name="amzn2-ami-hvm-2.*.1-x86_64-gp2"
device_type="ebs"
virtual_type="hvm"
ami_name="amazon-linux-2-ami"
ssh_username="ec2-user"
ssh_timeout="2h"

ami_user="479106608233"
owner="amazon"